# Generated by Django 5.2 on 2025-11-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pro_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bnm', models.CharField(max_length=25)),
                ('prc', models.IntegerField()),
                ('pimg', models.FileField(upload_to='pic')),
                ('des', models.TextField()),
            ],
        ),
    ]
