# Generated by Django 5.2 on 2025-11-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_pro_tbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro_tbl',
            name='pimg',
            field=models.FileField(blank=True, null=True, upload_to='pics/'),
        ),
    ]
