# Generated by Django 5.2 on 2025-11-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_alter_pro_tbl_pimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro_tbl',
            name='pimg',
            field=models.FileField(default=1, upload_to='pic'),
            preserve_default=False,
        ),
    ]
