# Generated by Django 5.2 on 2025-11-18 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_alter_pro_tbl_pimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.reg_tbl')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.pro_tbl')),
            ],
        ),
    ]
